-- MySQL Script generated by MySQL Workbench
-- Thu Nov 29 17:21:45 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema overchain
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema overchain
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `overchain` DEFAULT CHARACTER SET utf8 ;
USE `overchain` ;

-- -----------------------------------------------------
-- Table `overchain`.`Questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `overchain`.`Questions` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Questions` TEXT NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `overchain`.`Answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `overchain`.`Answers` (
  `Questions_ID` INT NOT NULL AUTO_INCREMENT,
  `Answers` TEXT NOT NULL,
  PRIMARY KEY (`Questions_ID`),
  INDEX `fk_Answers_Questions_idx` (`Questions_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Answers_Questions`
    FOREIGN KEY (`Questions_ID`)
    REFERENCES `overchain`.`Questions` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
